### PR TITLE
Ported the UI Checklist from Eclipse Wiki

### PR DESCRIPTION
**Pull request by azoitl**
As part of that a first clean-up of linked guidelines in the ui guidelines document was performed.

### CODE REVIEW

**Comment by vogella** [comment]
Thanks @azoitl Can you update the updated ;-) links to the moved repo?

**Comment by azoitl** [comment]
> Thanks @azoitl Can you update the updated ;-) links to the moved repo?

Sure. Do you know how I can update my fork to fix it?

**Comment by laeubi** [comment]
> > Thanks @azoitl Can you update the updated ;-) links to the moved repo?
> 
> Sure. Do you know how I can update my fork to fix it?

I *think* there is no need to fix as github redirects everything by default.

**Comment by azoitl** [comment]
> > > Thanks @azoitl Can you update the updated ;-) links to the moved repo?
> > 
> > 
> > Sure. Do you know how I can update my fork to fix it?
> 
> I _think_ there is no need to fix as github redirects everything by default.

Did a refresh and everything is fine. Was to quick with my question.

**Comment by azoitl** [comment]
> Thanks @azoitl Can you update the updated ;-) links to the moved repo?

Done!

**Pull request merged**
