### PR TITLE
Added section numbering to all files

### PR DESCRIPTION
**Pull request by azoitl**
As we have rather large documents with many sections and subsections I added section numbering to all of them. I hope this helps readers to better orient themselves in the documents.

### CODE REVIEW

**Comment by Bananeweizen** [comment]
Please be aware that I've reverted almost all of this change in #25. It's not a good idea to apply Asciidoctor settings to each file separately.

**Comment by azoitl** [comment]
> Please be aware that I've reverted almost all of this change in #25. It's not a good idea to apply Asciidoctor settings to each file separately.

Thx for the information. I'm still very new to ascii doc. So I'm happy for any feedback where I messed up.

**Comment by Bananeweizen** [comment]
You didn't mess up. It's just easier to have common configuration for all documents in a central place, which might be the title page (if everything is included into one huge document), a file being included (like a C header) into every document for multiple files, or just the invocation of the Asciidoctor tooling (which is what I used here).

**Comment by azoitl** [comment]
Good to know thx.

**Pull request merged**
