### PR TITLE
Fixed all headlines

### PR DESCRIPTION
**Pull request by azoitl**

### CODE REVIEW

**Comment by vogella** [comment]
Please resolve conflicts

**Comment by azoitl** [comment]
> Please resolve conflicts

done

**Comment by vogella** [comment]
This branch cannot be rebased due to conflicts

**Comment by vogella** [comment]
> > Please resolve conflicts
> 
> done

There seem to be still some issues

**Comment by azoitl** [comment]
> > > Please resolve conflicts
> > 
> > 
> > done
> 
> There seem to be still some issues

It seems I messed up some of the PRs with that I had them to be built on top of each other. This one is already included in the previouse one. Therefore I will close it. Will have to look on the rest on how to fix them.

**Pull request closed without merging**
